# Generated by Django 3.0.3 on 2020-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kxy_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
