# Generated by Django 3.0.3 on 2020-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kxy_store', '0002_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(db_column='product_name', max_length=200),
        ),
        migrations.AlterModelTable(
            name='product',
            table='xky_product',
        ),
    ]
