# Generated by Django 3.0.3 on 2020-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kxy_store', '0003_auto_20200215_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
